# -*- coding: utf-8 -*-
"""issue#415.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MJC_DlVrcDOfFVsbILMU27UXr5gIud95
"""

import sbol3
class CustomLocationClass(sbol3.Location, sbol3.CustomIdentified):
    def __init__(self, sequence=sbol3.Sequence('my_seq', elements='atcg'),
                 *, type_uri=PYSBOL3_CUSTOM_LOCATION, identity=None'):


        
             self.foo_int = sbol3.IntProperty(PYSBOL3_CUSTOM_INT,
                                         0, math.inf)




//Calling the class
 custom_loc = CustomLocationClass()

Tried this and it worked. I removed the super as it is not that necessary and supplied eyword argments to init